# Generated by Django 5.1.13 on 2025-11-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=150)),
                ('estudio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedeEstudio', to='examen.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('ventas_estimadas', models.PositiveIntegerField()),
                ('estudio_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegoEstudio', to='examen.estudio')),
                ('plataforma', models.ManyToManyField(blank=True, related_name='videojuegoPlataforma', to='examen.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField()),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('critico', models.CharField(max_length=150)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisisVideojuego', to='examen.videojuego')),
            ],
        ),
    ]
